### ISSUE TITLE
WiredTiger as Storage memory

### ISSUE THREAD

**Issue by indiejoseph** [kodexlab/eleve#1]
I wonder have you considered to change LevelDB to MongoDB(WiredTiger)?
Since its performance is better than LevelDB.

https://github.com/wiredtiger/wiredtiger/wiki/LevelDB-Benchmark

**Comment by palkeo** [comment]
LevelDB seems to be enough for our needs, and we don't have the time to rewrite the code.
However feel free to submit a PR to use WiredTiger instead! If it's provably faster for us, and the code is still simple we will totally consider it!
